-- ============================================================
-- V1 基线：RAG 问答 Agent 初始表结构（H2，local profile 用）
--
-- 与 mysql/V1__init.sql 结构等价，仅为方言差异：
--   1) 去掉 ENGINE / CHARSET / COLLATE
--   2) AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   3) 去掉 ON UPDATE CURRENT_TIMESTAMP（H2 不支持，updated_at 由 JPA @UpdateTimestamp 维护）
--   4) 索引改为独立 CREATE INDEX（H2 不支持建表内联 INDEX 语法）
-- ============================================================

-- 会话表
CREATE TABLE IF NOT EXISTS conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  VARCHAR(100) NOT NULL,
    title       VARCHAR(255),
    user_name   VARCHAR(100),
    model       VARCHAR(50),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_conversations_session_id ON conversations (session_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations (created_at);

-- 消息表
CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    content         TEXT NOT NULL,
    tokens          INT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id)
        REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at);

-- 知识库表
CREATE TABLE IF NOT EXISTS knowledge_bases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    file_path    VARCHAR(500),
    file_name    VARCHAR(255),
    file_size    BIGINT,
    doc_count    INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_knowledge_bases_name ON knowledge_bases (name);
CREATE INDEX IF NOT EXISTS idx_knowledge_bases_created_by ON knowledge_bases (created_by);

-- 知识文档（分块）表
CREATE TABLE IF NOT EXISTS documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL,
    title             VARCHAR(500),
    content           TEXT NOT NULL,
    chunk_id          VARCHAR(100) NOT NULL,
    chunk_index       INT,
    tokens            INT,
    vector_id         VARCHAR(100),
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documents_knowledge_base FOREIGN KEY (knowledge_base_id)
        REFERENCES knowledge_bases (id) ON DELETE CASCADE,
    CONSTRAINT uk_knowledge_chunk UNIQUE (knowledge_base_id, chunk_id)
);

CREATE INDEX IF NOT EXISTS idx_documents_knowledge_base_id ON documents (knowledge_base_id);
CREATE INDEX IF NOT EXISTS idx_documents_chunk_id ON documents (chunk_id);

-- 长期记忆表
CREATE TABLE IF NOT EXISTS memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  VARCHAR(100) NOT NULL,
    memory_key  VARCHAR(255) NOT NULL,
    value       TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_session_key UNIQUE (session_id, memory_key)
);

CREATE INDEX IF NOT EXISTS idx_memories_session_id ON memories (session_id);
CREATE INDEX IF NOT EXISTS idx_memories_memory_key ON memories (memory_key);

-- 工具调用记录表
CREATE TABLE IF NOT EXISTS tool_calls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT,
    session_id      VARCHAR(100),
    tool_name       VARCHAR(100) NOT NULL,
    tool_input      TEXT,
    tool_output     TEXT,
    status          VARCHAR(20) DEFAULT 'SUCCESS',
    error_message   TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tool_calls_conversation_id ON tool_calls (conversation_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session_id ON tool_calls (session_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_tool_name ON tool_calls (tool_name);
CREATE INDEX IF NOT EXISTS idx_tool_calls_status ON tool_calls (status);

-- Token 使用统计表
CREATE TABLE IF NOT EXISTS token_usage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      VARCHAR(100),
    conversation_id BIGINT,
    input_tokens    INT DEFAULT 0,
    output_tokens   INT DEFAULT 0,
    total_tokens    INT DEFAULT 0,
    cost            DECIMAL(10, 6) DEFAULT 0.000000,
    date            DATE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_session_date UNIQUE (session_id, date)
);

CREATE INDEX IF NOT EXISTS idx_token_usage_session_id ON token_usage (session_id);
CREATE INDEX IF NOT EXISTS idx_token_usage_conversation_id ON token_usage (conversation_id);
CREATE INDEX IF NOT EXISTS idx_token_usage_date ON token_usage (date);

-- 用户偏好设置表
CREATE TABLE IF NOT EXISTS user_preferences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  VARCHAR(100) NOT NULL,
    nickname    VARCHAR(100),
    ai_name     VARCHAR(100),
    personality VARCHAR(20),
    preferences JSON,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_preferences_session_id UNIQUE (session_id)
);

CREATE INDEX IF NOT EXISTS idx_user_preferences_session_id ON user_preferences (session_id);
